name: First workflow

# Especifica el disparador para este flujo de trabajo.
on: [push, pull_request]

#jobs - Agrupa todos los trabajos que se ejecutan en el flujo de trabajo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # La palabra clave uses especifica que este paso se ejecutará la v1 de la acción: actions/checkout
      - uses: actions/checkout@v3

      - name: Hello Codelies!
        # La palabra clave run le dice al trabajo que ejecute un comando en el runner.
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: 😊 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Install dependencies
        working-directory: ./lessons/04-Testing_Infrastructure/04.1-Installing_dependencies_by_docker
        run: make composer-install

      - name: Start all the environment
        working-directory: ./lessons/04-Testing_Infrastructure/04.2-Installing_dependencies_by_docker
        run: make start

      - name: Wait for the environment to get up
        run: |
          while ! docker exec codelytv-php_ddd_skeleton-mooc-mysql mysqladmin --user=root --password= --host "127.0.0.1" ping --silent &> /dev/null ; do
              echo "Waiting for database connection..."
              sleep 2
          done
      - name: Run the tests
        working-directory: ./lessons/04-Testing_Infrastructure/04.2-Installing_dependencies_by_docker
        run: make test