name: First workflow

# Especifica el disparador para este flujo de trabajo.
on: [push, pull_request]

#jobs - Agrupa todos los trabajos que se ejecutan en el flujo de trabajo
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # versiones de sistemas operativos y versiones de php
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2', '7.3', '7.4']

    name: ${{ matrix.os }} PHP ${{ matrix.php-versions }} # los nombres son requeridos cuando son varias versiones
    steps:
      # La palabra clave uses especifica que este paso se ejecutará la v1 de la acción: actions/checkout
      - uses: actions/checkout@v3

      - name: Hello Codelies!
        # La palabra clave run le dice al trabajo que ejecute un comando en el runner.
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: 😊 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      # condicionales - solo si es Windows
      - name: Greeting if Windows
        if: matrix.os == 'windows-latest'
        run: echo "Hey from Win2!"

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        working-directory: ./
        run: composer install --ignore-platform-reqs

      - name: Run the tests
        working-directory: ./
        run: composer phpunit
